import {BadRequestException,ConflictException,ForbiddenException,NotFoundException} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {Clinic} from './service';
import {allow,type Actor} from './access';
import type {Queryable} from './db';
const id=z.string().uuid(), short=z.string().trim().min(1).max(200), body=z.string().trim().min(1).max(20000);
const optionalId=id.nullable().optional();
const patientInput=z.object({name:short,birth_date:z.string().date().nullable().optional(),phone:z.string().max(50).default(''),address:z.string().max(1000).default(''),emergency_contact:z.string().max(1000).default(''),bed_id:optionalId,doctor_id:optionalId,referral:z.string().max(4000).default(''),care_type:z.enum(['INPATIENT','OUTPATIENT']).default('INPATIENT'),duplicate_ack:z.boolean().default(false)});

export class Care extends Clinic {
 async dashboard(a:Actor){allow(a,'dashboard');const worker=['NURSE','THERAPIST'].includes(a.role);if(worker){const active=await this.onShift(a);return {active:0,beds:0,occupied:0,open:active?Number((await this.db.query("SELECT count(*) FROM tasks WHERE status='OPEN' AND executor_role=$1",[a.role])).rows[0].count):0,mine:Number((await this.db.query("SELECT count(*) FROM tasks WHERE status='IN_PROGRESS' AND taken_by=$1",[a.id])).rows[0].count),completed:Number((await this.db.query("SELECT count(*) FROM tasks WHERE status='COMPLETED' AND NOT not_done AND taken_by=$1 AND completed_at>=current_date",[a.id])).rows[0].count)};}const result=await super.dashboard(a);result.completed=Number((await this.db.query("SELECT count(*) FROM tasks WHERE status='COMPLETED' AND NOT not_done AND completed_at>=current_date")).rows[0].count);return result;}
 async admission(c:Queryable,patientId:string){await this.activePatient(c,patientId);const row=(await c.query('SELECT * FROM admissions WHERE patient_id=$1 AND discharged_at IS NULL FOR UPDATE',[patientId])).rows[0];if(!row)throw new ConflictException('Немає активної госпіталізації');return row;}
 async reader(a:Actor,patientId:string){const p=await super.patient(a,patientId);return p;}
 async worker(a:Actor,c:Queryable=this.db){if(['NURSE','THERAPIST'].includes(a.role)&&!await this.onShift(a,c))throw new ForbiddenException('Почніть зміну');}
 async staff(a:Actor){allow(a,'patients.read');return (await this.db.query("SELECT id,name,role,specialty FROM users WHERE active AND role IN ('DOCTOR','NURSE','THERAPIST') ORDER BY name")).rows;}
 async patients(a:Actor,q:any){allow(a,q.status==='ARCHIVED'?'archive.read':'patients.read');const search=z.string().max(200).parse(q.q??'');const offset=z.coerce.number().int().min(0).parse(q.offset??0);
  return (await this.db.query("SELECT p.*,ad.id AS admission_id,ad.doctor_id,ad.doctor_since,ad.doctor_since+interval '15 days' AS handover_due,ad.care_type,ad.referral,u.name AS doctor_name,b.id AS bed_id,b.bed_number,r.room_number,r.floor FROM patients p LEFT JOIN admissions ad ON ad.patient_id=p.id AND ad.discharged_at IS NULL LEFT JOIN users u ON u.id=ad.doctor_id LEFT JOIN beds b ON b.id=ad.bed_id LEFT JOIN rooms r ON r.id=b.room_id WHERE p.status=$1 AND (p.name ILIKE $2 OR p.phone ILIKE $2 OR p.birth_date::text ILIKE $2) AND ($3::uuid IS NULL OR ad.doctor_id=$3) ORDER BY p.name,p.id LIMIT 100 OFFSET $4",[q.status==='ARCHIVED'?'ARCHIVED':'ACTIVE','%'+search+'%',q.mine==='true'&&a.role==='DOCTOR'?a.id:null,offset])).rows;
 }
 async duplicates(a:Actor,q:any){allow(a,'patients.manage');const name=z.string().max(200).parse(q.name??'');const phone=z.string().max(50).parse(q.phone??'');if(name.length<3&&phone.length<5)return [];return (await this.db.query("SELECT id,name,birth_date,phone,status FROM patients WHERE (length($1)>2 AND lower(name)=lower($1)) OR (length($2)>4 AND phone=$2) ORDER BY name LIMIT 30",[name,phone])).rows;}
 async register(a:Actor,input:any){allow(a,'patients.manage');const b=patientInput.parse(input);return this.db.tx(async c=>{
  await c.query('SELECT pg_advisory_xact_lock(780130)');
  const dup=(await c.query("SELECT id FROM patients WHERE lower(name)=lower($1) AND birth_date IS NOT DISTINCT FROM $2::date",[b.name,b.birth_date??null])).rows;
  if(dup.length&&!b.duplicate_ack)throw new ConflictException('Схожа картка вже існує. Перевірте дублікати або підтвердьте створення іншої людини.');
  await this.validateDoctor(c,b.doctor_id);
  const p=(await c.query('INSERT INTO patients(name,birth_date,phone,address,emergency_contact) VALUES($1,$2,$3,$4,$5) RETURNING *',[b.name,b.birth_date??null,b.phone,b.address,b.emergency_contact])).rows[0];
  await c.query('INSERT INTO admissions(patient_id,bed_id,doctor_id,referral,care_type) VALUES($1,$2,$3,$4,$5)',[p.id,b.care_type==='OUTPATIENT'?null:b.bed_id??null,b.doctor_id??null,b.referral,b.care_type]);await this.audit(c,a,'patient.registered',p.id);await this.changed(c);return p;
 });}
 async editPatient(a:Actor,patientId:string,input:any){allow(a,'patients.manage');id.parse(patientId);const b=patientInput.parse(input);return this.db.tx(async c=>{const ad=await this.admission(c,patientId);
  if(ad.doctor_id&&b.doctor_id!==ad.doctor_id)throw new ConflictException('Зміну лікуючого лікаря виконуйте через передачу пацієнта');
  await this.validateDoctor(c,b.doctor_id);
  await c.query("INSERT INTO patient_revisions(patient_id,actor_id,previous) SELECT id,$2,to_jsonb(p)||jsonb_build_object('admission',(SELECT to_jsonb(ad) FROM admissions ad WHERE ad.patient_id=p.id AND ad.discharged_at IS NULL)) FROM patients p WHERE id=$1",[patientId,a.id]);
  await c.query('UPDATE patients SET name=$2,birth_date=$3,phone=$4,address=$5,emergency_contact=$6 WHERE id=$1',[patientId,b.name,b.birth_date??null,b.phone,b.address,b.emergency_contact]);
  await c.query('UPDATE admissions SET bed_id=$2,doctor_id=$3,referral=$4,care_type=$5,doctor_since=CASE WHEN doctor_id IS DISTINCT FROM $3::uuid THEN now() ELSE doctor_since END WHERE id=$1',[ad.id,b.care_type==='OUTPATIENT'?null:b.bed_id??null,b.doctor_id??null,b.referral,b.care_type]);await this.audit(c,a,'patient.updated',patientId);await this.changed(c);return {id:patientId};
 });}
 async readmit(a:Actor,patientId:string,input:any){allow(a,'patients.manage');id.parse(patientId);const b=patientInput.pick({bed_id:true,doctor_id:true,referral:true,care_type:true}).parse(input);return this.db.tx(async c=>{const p=(await c.query('SELECT status FROM patients WHERE id=$1 FOR UPDATE',[patientId])).rows[0];if(!p)throw new NotFoundException();if(p.status!=='ARCHIVED')throw new ConflictException('Пацієнт вже активний');await this.validateDoctor(c,b.doctor_id);await c.query('INSERT INTO admissions(patient_id,bed_id,doctor_id,referral,care_type) VALUES($1,$2,$3,$4,$5)',[patientId,b.care_type==='OUTPATIENT'?null:b.bed_id??null,b.doctor_id??null,b.referral,b.care_type]);await c.query("UPDATE patients SET status='ACTIVE' WHERE id=$1",[patientId]);await this.audit(c,a,'patient.readmitted',patientId);await this.changed(c);return {id:patientId};});}
 async discharge(a:Actor,patientId:string){allow(a,'patients.manage');id.parse(patientId);return this.db.tx(async c=>{const ad=await this.admission(c,patientId);await c.query("UPDATE care_handovers SET status='CANCELLED' WHERE admission_id=$1 AND status='PENDING'",[ad.id]);await c.query("UPDATE tasks SET status='CANCELLED' WHERE admission_id=$1 AND status IN ('OPEN','IN_PROGRESS')",[ad.id]);await c.query("UPDATE appointments SET status='CANCELLED' WHERE patient_id=$1 AND status='BOOKED' AND ends_at>now()",[patientId]);await c.query('UPDATE admissions SET discharged_at=now() WHERE id=$1',[ad.id]);await c.query("UPDATE patients SET status='ARCHIVED' WHERE id=$1",[patientId]);await this.audit(c,a,'patient.discharged',patientId);await this.changed(c);return {ok:true};});}
 async patient(a:Actor,patientId:string,qr=false){const p=await super.patient(a,patientId,qr);if(qr&&a.role==='NURSE')return p;
  const clinical=a.permissions.some(p=>['clinical.write','observations.write','rehab.write'].includes(p));
  return {...p,entries:clinical?(await this.db.query('SELECT e.*,u.name AS author FROM clinical_entries e JOIN users u ON u.id=e.author_id JOIN admissions ad ON ad.id=e.admission_id WHERE ad.patient_id=$1 ORDER BY e.created_at DESC',[patientId])).rows:[],documents:(await this.db.query('SELECT id,filename,mime,created_at,admission_id FROM patient_documents WHERE patient_id=$1 ORDER BY created_at DESC',[patientId])).rows,
   handovers:(await this.db.query('SELECT h.*,f.name AS from_name,t.name AS to_name FROM care_handovers h JOIN admissions ad ON ad.id=h.admission_id JOIN users f ON f.id=h.from_id JOIN users t ON t.id=h.to_id WHERE ad.patient_id=$1 ORDER BY h.created_at DESC',[patientId])).rows};
 }
 async entry(a:Actor,patientId:string,input:any){id.parse(patientId);const b=z.object({kind:z.enum(['ASSESSMENT','OBSERVATION','REHAB','DISCHARGE','CORRECTION']),body,data:z.record(z.string(),z.unknown()).default({}),corrects_id:optionalId}).parse(input);
  const permission=b.kind==='OBSERVATION'?'observations.write':b.kind==='REHAB'?'rehab.write':'clinical.write';if(b.kind==='CORRECTION'){if(!a.permissions.some(p=>['clinical.write','observations.write','rehab.write'].includes(p)))throw new ForbiddenException();}else allow(a,permission);
  if(b.kind==='OBSERVATION')b.data=z.object({systolic:z.number().min(20).max(350).optional(),diastolic:z.number().min(10).max(250).optional(),pulse:z.number().min(0).max(350).optional(),temperature:z.number().min(20).max(50).optional(),spo2:z.number().min(0).max(100).optional(),glucose:z.number().min(0).max(100).optional(),pain:z.number().int().min(0).max(10).optional(),observed_at:z.string().datetime({offset:true})}).parse(b.data);
  if(b.kind==='ASSESSMENT')b.data=z.object({diagnosis:z.string().max(4000),allergies:z.string().max(4000),plan:z.string().max(10000)}).parse(b.data);
  if(b.kind==='REHAB')b.data=z.object({goals:z.string().max(4000),assessment:z.string().max(4000),result:z.string().max(4000),next_plan:z.string().max(4000)}).parse(b.data);
  if(b.kind==='DISCHARGE')b.data=z.object({recommendations:z.string().max(10000),follow_up:z.string().max(4000)}).parse(b.data);
  if(JSON.stringify(b.data).length>20000)throw new BadRequestException('Завеликий запис');
  return this.db.tx(async c=>{const ad=await this.admission(c,patientId);await this.worker(a,c);
   if(b.kind==='CORRECTION'){if(!b.corrects_id||!(await c.query('SELECT id FROM clinical_entries WHERE id=$1 AND admission_id=$2 AND author_id=$3',[b.corrects_id,ad.id,a.id])).rows.length)throw new ForbiddenException('Виправляти можна власний запис цієї госпіталізації');}else if(b.corrects_id)throw new BadRequestException('Посилання дозволене лише для виправлення');
   const e=(await c.query('INSERT INTO clinical_entries(admission_id,author_id,kind,body,data,corrects_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[ad.id,a.id,b.kind,b.body,b.data,b.corrects_id??null])).rows[0];await this.audit(c,a,'clinical.'+b.kind.toLowerCase(),e.id);await this.changed(c);return e;
  });
 }
 async handovers(a:Actor){allow(a,'handover.manage');return (await this.db.query("SELECT h.*,p.name AS patient_name,p.id AS patient_id,f.name AS from_name,t.name AS to_name FROM care_handovers h JOIN admissions ad ON ad.id=h.admission_id JOIN patients p ON p.id=ad.patient_id JOIN users f ON f.id=h.from_id JOIN users t ON t.id=h.to_id WHERE h.from_id=$1 OR h.to_id=$1 ORDER BY h.created_at DESC LIMIT 500",[a.id])).rows;}
 async handover(a:Actor,input:any){allow(a,'handover.manage');const b=z.object({patient_ids:z.array(id).min(1).max(500),to_id:id,summary:body}).parse(input);if(a.id===b.to_id)throw new BadRequestException('Оберіть іншого лікаря');
  return this.db.tx(async c=>{await this.validateDoctor(c,b.to_id);const ids=[...new Set(b.patient_ids)].sort();for(const patientId of ids){const ad=await this.admission(c,patientId);if(ad.doctor_id!==a.id)throw new ForbiddenException('Передавати можна лише своїх пацієнтів');const h=(await c.query('INSERT INTO care_handovers(admission_id,from_id,to_id,summary) VALUES($1,$2,$3,$4) RETURNING id',[ad.id,a.id,b.to_id,b.summary])).rows[0];await this.audit(c,a,'handover.requested',h.id);}await this.changed(c);return {count:ids.length};});
 }
 async acceptHandover(a:Actor,handoverId:string,action:string){allow(a,'handover.manage');id.parse(handoverId);if(!['accept','cancel'].includes(action))throw new BadRequestException();return this.db.tx(async c=>{
  const ref=(await c.query('SELECT ad.patient_id FROM care_handovers h JOIN admissions ad ON ad.id=h.admission_id WHERE h.id=$1',[handoverId])).rows[0];if(!ref)throw new NotFoundException();const ad=await this.admission(c,ref.patient_id);
  const h=(await c.query('SELECT * FROM care_handovers WHERE id=$1 FOR UPDATE',[handoverId])).rows[0];if(h.status!=='PENDING'||h.admission_id!==ad.id||h.from_id!==ad.doctor_id)throw new ConflictException('Передачу вже змінено');
  if(action==='accept'){if(a.id!==h.to_id)throw new ForbiddenException('Прийняти може лише вказаний лікар');await this.validateDoctor(c,a.id);await c.query('UPDATE admissions SET doctor_id=$2,doctor_since=now() WHERE id=$1',[ad.id,a.id]);}
  else if(a.id!==h.from_id&&a.id!==h.to_id)throw new ForbiddenException();
  await c.query("UPDATE care_handovers SET status=$2,accepted_at=CASE WHEN $2='ACCEPTED' THEN now() ELSE NULL END WHERE id=$1",[h.id,action==='accept'?'ACCEPTED':'CANCELLED']);await this.audit(c,a,'handover.'+action,h.id);await this.changed(c);return {ok:true};
 });}
 async messages(a:Actor){allow(a,'messages.use');return (await this.db.query('SELECT m.*,s.name AS sender,r.name AS recipient,p.name AS patient_name FROM care_messages m JOIN users s ON s.id=m.sender_id JOIN users r ON r.id=m.recipient_id LEFT JOIN patients p ON p.id=m.patient_id WHERE m.sender_id=$1 OR m.recipient_id=$1 ORDER BY m.created_at DESC LIMIT 200',[a.id])).rows;}
 async message(a:Actor,input:any){allow(a,'messages.send');const b=z.object({patient_id:optionalId,recipient_id:id,body,urgent:z.boolean().default(false)}).parse(input);if(b.patient_id)await this.reader(a,b.patient_id);return this.db.tx(async c=>{if(!(await c.query('SELECT id FROM users WHERE id=$1 AND active',[b.recipient_id])).rows.length)throw new BadRequestException('Працівник недоступний');const m=(await c.query('INSERT INTO care_messages(patient_id,sender_id,recipient_id,body,urgent) VALUES($1,$2,$3,$4,$5) RETURNING *',[b.patient_id??null,a.id,b.recipient_id,b.body,b.urgent])).rows[0];await this.audit(c,a,'message.sent',m.id);await this.changed(c);return m;});}
 async readMessage(a:Actor,messageId:string){allow(a,'messages.use');id.parse(messageId);const r=(await this.db.query('UPDATE care_messages SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND recipient_id=$2 RETURNING id',[messageId,a.id])).rows[0];if(!r)throw new NotFoundException();return r;}
 async document(a:Actor,documentId:string){id.parse(documentId);const d=(await this.db.query('SELECT * FROM patient_documents WHERE id=$1',[documentId])).rows[0];if(!d)throw new NotFoundException();await this.reader(a,d.patient_id);await this.audit(this.db,a,'document.read',d.id);return d;}
 async upload(a:Actor,patientId:string,input:any){allow(a,'documents.manage');await this.reader(a,patientId);const b=z.object({filename:short,mime:z.enum(['application/pdf','image/jpeg','image/png']),base64:z.string().max(7000000)}).parse(input);if(!/^[A-Za-z0-9+/]*={0,2}$/.test(b.base64))throw new BadRequestException();const bytes=Buffer.from(b.base64,'base64');if(!bytes.length||bytes.length>5*1024*1024)throw new BadRequestException('Максимум 5 МБ');const valid=b.mime==='application/pdf'?bytes.subarray(0,5).toString()==='%PDF-':b.mime==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)throw new BadRequestException('Формат файлу не відповідає вмісту');return this.db.tx(async c=>{const ad=await this.admission(c,patientId);const d=(await c.query('INSERT INTO patient_documents(patient_id,admission_id,author_id,filename,mime,content) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[patientId,ad.id,a.id,b.filename,b.mime,bytes])).rows[0];await this.audit(c,a,'document.uploaded',d.id);return d;});}
 async teamHandovers(a:Actor){allow(a,'shift.handover');return (await this.db.query('SELECT h.*,u.name AS author,v.name AS recipient FROM team_handovers h JOIN users u ON u.id=h.author_id JOIN users v ON v.id=h.recipient_id WHERE h.author_id=$1 OR h.recipient_id=$1 ORDER BY h.created_at DESC LIMIT 100',[a.id])).rows;}
 async teamHandover(a:Actor,input:any){allow(a,'shift.handover');const b=z.object({recipient_id:id,summary:body}).parse(input);if(b.recipient_id===a.id)throw new BadRequestException('Оберіть іншого працівника');return this.db.tx(async c=>{await c.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[a.id]);await this.worker(a,c);if(!(await c.query('SELECT id FROM users WHERE id=$1 AND role=$2 AND active',[b.recipient_id,a.role])).rows.length)throw new BadRequestException('Оберіть працівника своєї ролі');if((await c.query('SELECT id FROM team_handovers WHERE author_id=$1 AND accepted_at IS NULL',[a.id])).rows.length)throw new ConflictException('Попередню передачу ще не прийнято');const tasks=(await c.query("SELECT id FROM tasks WHERE taken_by=$1 AND status='IN_PROGRESS' ORDER BY id",[a.id])).rows;
   const h=(await c.query('INSERT INTO team_handovers(author_id,recipient_id,summary,task_ids) VALUES($1,$2,$3,$4) RETURNING *',[a.id,b.recipient_id,b.summary,tasks.map(t=>t.id)])).rows[0];await this.audit(c,a,'team.handover',h.id);await this.changed(c);return h;
 });}
 async acceptTeam(a:Actor,transferId:string){allow(a,'shift.handover');id.parse(transferId);return this.db.tx(async c=>{
  const h=(await c.query('SELECT * FROM team_handovers WHERE id=$1',[transferId])).rows[0];if(!h)throw new NotFoundException();if(h.recipient_id!==a.id)throw new ForbiddenException();
  const pts=(await c.query('SELECT DISTINCT patient_id FROM tasks WHERE id=ANY($1::uuid[]) ORDER BY patient_id',[h.task_ids])).rows;for(const p of pts)await c.query('SELECT id FROM patients WHERE id=$1 FOR UPDATE',[p.patient_id]);
  await c.query('SELECT id FROM users WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE',[[a.id,h.author_id]]);await this.worker(a,c);
  const locked=(await c.query('SELECT * FROM team_handovers WHERE id=$1 FOR UPDATE',[transferId])).rows[0];if(locked.accepted_at)throw new ConflictException('Вже прийнято');
  // Closed or returned tasks are not resurrected. Only remaining owned work moves.
  await c.query("UPDATE tasks SET taken_by=$2 WHERE id=ANY($1::uuid[]) AND taken_by=$3 AND status='IN_PROGRESS' AND executor_role=$4",[h.task_ids,a.id,h.author_id,a.role]);
  await c.query('UPDATE team_handovers SET accepted_at=now() WHERE id=$1',[h.id]);
  await c.query("UPDATE shifts SET ends_at=GREATEST(now(),starts_at+interval '1 millisecond') WHERE user_id=$1 AND ends_at>now() AND NOT EXISTS(SELECT 1 FROM tasks WHERE taken_by=$1 AND status='IN_PROGRESS')",[h.author_id]);await this.audit(c,a,'team.accepted',h.id);await this.changed(c);return {ok:true};
 });}
 async rooms(a:Actor){const rows=await super.rooms(a);const floors=(await this.db.query('SELECT id,floor FROM rooms')).rows;return rows.map(r=>({...r,floor:floors.find(f=>f.id===r.id)?.floor||''}));}
 async room(a:Actor,input:any){allow(a,'rooms.manage');const b=z.object({room_number:short,floor:z.string().max(50).default('')}).parse(input);return this.db.tx(async c=>{const r=(await c.query('INSERT INTO rooms(room_number,floor) VALUES($1,$2) RETURNING *',[b.room_number,b.floor])).rows[0];await this.audit(c,a,'room.created',r.id);return r;});}
 async appointments(a:Actor,q:any={}){if(!a.permissions.some(p=>['cabinets.manage','appointments.read'].includes(p)))throw new ForbiddenException();await this.worker(a);return (await this.db.query("SELECT ap.*,p.name AS patient_name,c.name AS cabinet_name,u.name AS staff_name FROM appointments ap JOIN patients p ON p.id=ap.patient_id JOIN cabinets c ON c.id=ap.cabinet_id LEFT JOIN users u ON u.id=ap.staff_id WHERE ap.starts_at>=now()-interval '7 days' AND ($1::uuid IS NULL OR ap.staff_id=$1) ORDER BY ap.starts_at LIMIT 1000",[q.mine==='true'?a.id:null])).rows;}
 async appointment(a:Actor,input:any){allow(a,'appointments.manage');const b=z.object({patient_id:id,cabinet_id:id,staff_id:optionalId,starts_at:z.string().datetime({offset:true}),ends_at:z.string().datetime({offset:true})}).parse(input);if(new Date(b.ends_at)<=new Date(b.starts_at))throw new BadRequestException('Кінець має бути після початку');return this.db.tx(async c=>{await this.activePatient(c,b.patient_id);if(b.staff_id&&!(await c.query("SELECT id FROM users WHERE id=$1 AND active AND role IN ('DOCTOR','THERAPIST','NURSE') FOR UPDATE",[b.staff_id])).rows.length)throw new BadRequestException('Працівник недоступний');if(!(await c.query('SELECT id FROM cabinets WHERE id=$1 FOR UPDATE',[b.cabinet_id])).rows.length)throw new NotFoundException();if((await c.query("SELECT id FROM appointments WHERE status='BOOKED' AND (patient_id=$1 OR cabinet_id=$2 OR staff_id=$3) AND starts_at<$5 AND ends_at>$4",[b.patient_id,b.cabinet_id,b.staff_id??null,b.starts_at,b.ends_at])).rows.length)throw new ConflictException('Пацієнт, кабінет або спеціаліст зайнятий');const row=(await c.query('INSERT INTO appointments(patient_id,cabinet_id,staff_id,starts_at,ends_at,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[b.patient_id,b.cabinet_id,b.staff_id??null,b.starts_at,b.ends_at,a.id])).rows[0];await this.audit(c,a,'appointment.created',row.id);await this.changed(c);return row;});}
 async finishWork(a:Actor){return this.db.tx(async c=>{await c.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[a.id]);if((await c.query("SELECT id FROM tasks WHERE taken_by=$1 AND status='IN_PROGRESS'",[a.id])).rows.length)throw new ConflictException('Спочатку завершіть або передайте свої завдання. Зміну не завершено.');await c.query("UPDATE shifts SET ends_at=GREATEST(now(),starts_at+interval '1 millisecond') WHERE user_id=$1 AND ends_at>now()",[a.id]);await c.query('UPDATE sessions SET revoked_at=now() WHERE id=$1',[a.sid]);await this.audit(c,a,'work.finished',a.id);return {ok:true};});}
 async alerts(a:Actor){allow(a,'messages.use');const unread=Number((await this.db.query('SELECT count(*) FROM care_messages WHERE recipient_id=$1 AND read_at IS NULL',[a.id])).rows[0].count);const due=a.role==='DOCTOR'?Number((await this.db.query("SELECT count(*) FROM admissions WHERE doctor_id=$1 AND discharged_at IS NULL AND doctor_since<=now()-interval '15 days'",[a.id])).rows[0].count):0;return {unread,due};}
 async tasks(a:Actor){const worker=['NURSE','THERAPIST'].includes(a.role);allow(a,worker?'tasks.work':'tasks.read');await this.worker(a);return (await this.db.query("SELECT t.*,p.name AS patient_name,p.birth_date,u.name AS nurse_name,c.name AS cabinet_name,r.room_number,r.floor FROM tasks t JOIN patients p ON p.id=t.patient_id JOIN admissions ad ON ad.id=t.admission_id LEFT JOIN beds b ON b.id=ad.bed_id LEFT JOIN rooms r ON r.id=b.room_id LEFT JOIN users u ON u.id=t.taken_by LEFT JOIN cabinets c ON c.id=t.cabinet_id WHERE ($1::text IS NULL OR (t.executor_role=$1 AND (t.status='OPEN' OR t.taken_by=$2))) AND (t.status IN ('OPEN','IN_PROGRESS') OR t.created_at>now()-interval '7 days') ORDER BY t.scheduled_at LIMIT 1000",[worker?a.role:null,a.id])).rows;}
 async task(a:Actor,input:any){allow(a,'tasks.create');const b=z.object({patient_id:id,description:z.string().trim().min(1).max(4000),task_type:short,scheduled_at:z.string().datetime({offset:true}),cabinet_id:optionalId,executor_role:z.enum(['NURSE','THERAPIST']).default('NURSE'),medication:z.string().max(200).default(''),dose:z.string().max(100).default(''),dose_unit:z.string().max(50).default(''),route:z.string().max(100).default(''),repeat_count:z.number().int().min(1).max(90).default(1),interval_hours:z.number().min(1).max(720).default(24)}).parse(input);
  if(b.medication&&(!b.dose||!b.dose_unit||!b.route||b.executor_role!=='NURSE'))throw new BadRequestException('Для ліків вкажіть дозу, одиниці та шлях введення; виконавець — медсестра');
  return this.db.tx(async c=>{const ad=await this.admission(c,b.patient_id),course=randomUUID();const rows=[];for(let n=0;n<b.repeat_count;n++){const scheduled=new Date(new Date(b.scheduled_at).getTime()+n*b.interval_hours*3600000).toISOString();rows.push((await c.query('INSERT INTO tasks(patient_id,admission_id,created_by,description,task_type,scheduled_at,cabinet_id,executor_role,medication,dose,dose_unit,route,course_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[b.patient_id,ad.id,a.id,b.description,b.task_type,scheduled,b.cabinet_id??null,b.executor_role,b.medication,b.dose,b.dose_unit,b.route,course])).rows[0]);}await this.audit(c,a,'course.created',course);await this.changed(c);return {...rows[0],count:rows.length};});
 }
 async taskAction(a:Actor,taskId:string,action:string,input:any={}){id.parse(taskId);if(!['claim','complete','release','cancel','not-done'].includes(action))throw new NotFoundException();allow(a,action==='cancel'?'tasks.create':'tasks.work');const b=z.object({outcome:z.string().trim().max(4000).default(''),identity_confirmed:z.boolean().default(false)}).parse(input);if(['complete','not-done'].includes(action)&&!b.identity_confirmed)throw new BadRequestException('Підтвердіть ПІБ і дату народження пацієнта');if(action==='not-done'&&!b.outcome)throw new BadRequestException('Вкажіть причину невиконання');
  return this.db.tx(async c=>{const ref=(await c.query('SELECT patient_id FROM tasks WHERE id=$1',[taskId])).rows[0];if(!ref)throw new NotFoundException();await this.activePatient(c,ref.patient_id);if(action!=='cancel'){await c.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[a.id]);await this.worker(a,c);}
   const t=(await c.query('SELECT * FROM tasks WHERE id=$1 FOR UPDATE',[taskId])).rows[0];if(action==='cancel'){if(t.created_by!==a.id||!['OPEN','IN_PROGRESS'].includes(t.status))throw new ConflictException('Завдання вже закрито або належить іншому лікарю');await c.query("UPDATE tasks SET status='CANCELLED' WHERE id=$1",[taskId]);}
   else {if(t.executor_role!==a.role)throw new ForbiddenException('Завдання для іншої ролі');if(action==='claim'){if(t.status!=='OPEN')throw new ConflictException('Завдання вже взято');await c.query("UPDATE tasks SET status='IN_PROGRESS',taken_by=$2,taken_at=now() WHERE id=$1",[taskId,a.id]);}
    else {if(t.status!=='IN_PROGRESS'||t.taken_by!==a.id)throw new ConflictException('Завдання вже змінено або має іншого виконавця');if(action==='release')await c.query("UPDATE tasks SET status='OPEN',taken_by=NULL,taken_at=NULL WHERE id=$1",[taskId]);else await c.query("UPDATE tasks SET status='COMPLETED',completed_at=now(),outcome=$2,not_done=$3 WHERE id=$1",[taskId,b.outcome,action==='not-done']);}}
   await this.audit(c,a,'task.'+action,taskId);await this.changed(c);return (await c.query('SELECT * FROM tasks WHERE id=$1',[taskId])).rows[0];
  });
 }
}
