import React,{useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {api,token} from './api';
function owner(){try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).sub as string}catch{return ''}}
let database:Promise<IDBDatabase>|undefined;
function db(){return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('rehaflow-private-drafts',1);r.onupgradeneeded=()=>r.result.createObjectStore('keys');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function key(user:string){const d=await db();const existing=await new Promise<CryptoKey|undefined>((resolve,reject)=>{const r=d.transaction('keys').objectStore('keys').get(user);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(existing)return existing;const generated=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);return new Promise<CryptoKey>((resolve,reject)=>{const t=d.transaction('keys','readwrite'),s=t.objectStore('keys'),r=s.get(user);let result=generated;r.onsuccess=()=>{if(r.result)result=r.result;else s.put(generated,user)};t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error)})}
const prefix='rehaflow.draft.v4:';
const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const b64=(b:Uint8Array)=>btoa(Array.from(b,x=>String.fromCharCode(x)).join(''));
export async function draftRead(scope:string,user=owner()){if(!user)return null;const raw=localStorage.getItem(prefix+user+':'+scope);if(!raw)return null;const e=JSON.parse(raw);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(e.iv),additionalData:new TextEncoder().encode(user+':'+scope)},await key(user),bytes(e.data));const value=JSON.parse(new TextDecoder().decode(plain));if(!value.locked&&Date.now()-e.at>7*86400000){draftRemove(scope,user);return null}return value}
export async function draftWrite(scope:string,value:any,user=owner()){if(!user)throw Error('Увійдіть для збереження чернетки');const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(user+':'+scope)},await key(user),new TextEncoder().encode(JSON.stringify(value)));localStorage.setItem(prefix+user+':'+scope,JSON.stringify({at:Date.now(),iv:b64(iv),data:b64(new Uint8Array(data))}))}
export function draftRemove(scope:string,user=owner()){localStorage.removeItem(prefix+user+':'+scope)}
export function DraftForm({scope,children,submit,label='Зберегти',onRestore}:{scope:string;children:ReactNode;submit:(d:FormData)=>Promise<unknown>;label?:string;onRestore?:(v:Record<string,string>)=>void}){
 const [record,setRecord]=useState<any>(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[storageBlocked,setStorageBlocked]=useState(false);const chain=useRef(Promise.resolve());const principal=useRef(owner()).current;const restore=useRef(onRestore);restore.current=onRestore;
 useEffect(()=>{let live=true;draftRead(scope,principal).then(r=>{if(!live)return;const next=r??{id:crypto.randomUUID(),values:{},locked:false};setRecord(next);if(r){restore.current?.(r.values);setStatus('Чернетку відновлено. Перевірте дані перед надсиланням.')}}).catch(()=>{if(live){setStorageBlocked(true);setRecord({id:crypto.randomUUID(),values:{},locked:false});setError('Сховище чернеток недоступне. Перевірте налаштування браузера.')}});return()=>{live=false}},[scope]);
 function persist(next:any){setRecord(next);chain.current=chain.current.catch(()=>{}).then(()=>draftWrite(scope,next,principal));chain.current.then(()=>setStatus(next.locked?'Відповідь не підтверджена. Повторіть ту саму операцію.':'Чернетку збережено на цьому пристрої · 7 днів')).catch(()=>setError('Не вдалося зберегти чернетку на пристрої.'))}
 function controls(nodes:ReactNode):ReactNode{return React.Children.map(nodes,(child)=>{if(!React.isValidElement(child))return child;const el=child as React.ReactElement<any>,p=el.props;if(['input','textarea','select'].includes(String(el.type))&&p.name&&p.type!=='file'&&p.type!=='password'&&p.type!=='hidden'){const v=record.values[p.name];return React.cloneElement(el,{...(v!==undefined?(p.type==='checkbox'?{checked:v==='true'||v==='on',defaultChecked:undefined}:{value:v,defaultValue:undefined}):{}),onChange:(e:any)=>{p.onChange?.(e);const form=e.target.closest('form');const values=Object.fromEntries(new FormData(form).entries());persist({...record,values})}})}return p.children?React.cloneElement(el,{},controls(p.children)):el})}
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!record)return;setBusy(true);setError('');const d=new FormData(e.currentTarget);let values=record.values;if(!record.locked){values=Object.fromEntries([...d.entries()].map(([k,v])=>[k,String(v)]));const next={...record,values,locked:true};persist(next)}else{for(const[k,v]of Object.entries(values))d.set(k,String(v))}d.set('_request_id',record.id);try{await chain.current;await submit(d);await chain.current;draftRemove(scope,principal);setRecord({id:crypto.randomUUID(),values:{},locked:false});setStatus('Збережено на сервері')}catch(e){const x=e as any;setError(x.message);if(x.status===undefined||(x.status>0&&x.status<500)){persist({...record,values,locked:false})}}finally{setBusy(false)}}
 if(!record)return <p>Відкриваємо чернетку…</p>;
 return <form onSubmit={send}><p role="status" className="muted">{status||'Чернетка зберігатиметься на цьому пристрої.'}</p><fieldset disabled={busy||record.locked}>{controls(children)}</fieldset>{error&&<p className="error" role="alert">{error}</p>}<button className="primary submit" disabled={busy||storageBlocked}>{busy?'Очікуємо підтвердження…':record.locked?'Повторити збереження без дублювання':label}</button>{!record.locked&&<button type="button" className="ghost" disabled={busy} onClick={async()=>{if(!window.confirm('Видалити чернетку та очистити форму?'))return;await chain.current.catch(()=>{});draftRemove(scope,principal);window.location.reload()}}>Видалити чернетку</button>}</form>
}
